### ISSUE TITLE
GK LBO doesn't conserve energy with B=B(x)

### ISSUE THREAD

**Issue by manauref** [ammarhakim/gkylzero#304]
If you run a simple test, like rt_gk_lbo_relax_1x2v_p1 with a spatially varying magnetic field like 
```
  fout[0] = B0*(1.+0.5*cos(2.*M_PI*zc[2]));
```
you'll find that the kinetic energy (M2) is not conserved (you have to comment out cross-species collisions).

I believe this is because unlike g2, g0 is computing bmag_inv using the same procedure as with all other quantities, but instead bmag_inv should be computed with 1/bmag using weak division.

When this issue is addressed, some or all of the lbo reg tests should be modified to have B(x) instead.

**Comment by JunoRavin** [comment]
I can tell you from my experience with PKPM that precomputing 1/A, where A is a DG field, only works for p=1. Only in p=1 can you guarantee that B * 1/A * A = B from the pre-computed 1/A expansion. If you do this precomputation with p>1 you will see that you lose accuracy and it's really just coincidence that it works for p=1. This is because fundamentally what you are trying to guarantee is not a binary operation (we evolve J*f and you want to get f out, so really you're trying to extra (B*A)*1/A = B which is not a binary operation, it's a ternary operation). 

These sorts of issues are why I have been insistent that for computing moments one must use weak division to get rid of the Jacobian multiplying the moment because I knew the way 1/J was being computed would not produce (M*J)*1/J = M. 

At the end of the day you're going to have to change a lot of the underlying program flow for p>1 if you want to guarantee things like this. For example, for collisions here you will not be able to pre-compute 1/B. You will have to, at every time step, do a weak division of vth^2 and B to get the expansion of vth^2/B. Only for p=1 can you safely store a 1/B with the procedure you're describing

**Comment by JunoRavin** [comment]
Just for your reference on how bad this can be to pre-compute 1/A for p>1, I dug through old commits (going all the way back to this commit which is the PKPM commit before I fixed this: https://github.com/ammarhakim/gkylzero/commit/b52341d871587d816045b524857c0f88127cd59a)

In orange is the current main, in blue is PKPM solution at that time comparing the two heat flux moments (qparallel and qperp) for a parallel electrostatic shock (B is along x/z0). 

**Again, things are fine for p=1 and you can actually be extremely efficient for p=1 by not doing weak division and just using the basis_inv methods I wrote.**

But if you try to do this pre-computation for p>1, you can run into very serious issues from the accuracy degradation of not satisfying (B*A)*1/A = B. 

I only discovered this because of the way I was doing unit testing with the https://github.com/ammarhakim/gkylzero/blob/main/unit/ctest_dg_em_vars.c 

Because I was trying to make sure that I could compute things like E x B/B^2 as either 
1. E x B, then weak division by B^2
2. E x B * 1/B^2
and those two were only equivalent for p=1. For p=2 the differences were on the order of 1 percent. I assumed this was just a difference in representation until I looked at nonlinear simulations and saw that E x B * 1/B^2 is manifestly worse than E x B, then weak division by B^2. 

<img width="2235" alt="Screenshot 2024-03-13 at 8 40 53 AM" src="https://github.com/ammarhakim/gkylzero/assets/7997308/48e244e6-fd34-4ffb-a0a5-9a40e1800872">

**Comment by manauref** [comment]
Thanks for the detail @junoravin.
Since we are doing p=1 gyrokinetics at the moment we'll still want to fix
it so that it conserves energy. We'll deal with p=2 when we get there (i'd
actually be surprised if my suggestion doesn't fix p=2 as well, because I
remember checking LBO conservation for p=2 in g2 and don't remember any
problems there).

**Comment by JunoRavin** [comment]
The issue with pre-computing 1/A for a DG field A for p>1 is ultimately an aliasing effect that you can't guarantee (B*A)*1/A = B, so depending on the variation of the magnetic field, the errors may be sub-dominant. 

What I am saying is that you should be cautious about how you choose to fix this. It's fine to pre-compute 1/A (in this case 1/Bmag) for p=1 and you can make your lives easier by just using the basis_inv methods instead of having to set up a linear system to invert at t=0. In general the way I've approached this is to always use the basis_inv methods for p=1 because they are ludicrously efficient (over a factor of 10 faster than our bin_op weak division) and to switch to genuine weak division with bin_op for p>1.

**Comment by manauref** [comment]
This division only takes place once at t=0, so we don't have to worry about
efficiency and can use bin_op_div. If we find ourselves having to do
something like this in time, yes, we'll use basis_inv.

**Comment by JunoRavin** [comment]
Sure but you can save yourself the annoyance that you have to set up the bin_op memory and then free it when you're done, and you guard against future developers not realizing you **should not** do this for p>1 because the basis_inv methods don't exist for p>1.

**Comment by manauref** [comment]
Not sure because I think g2 p=2 LBO conserved energyOn Mar 13, 2024, at 7:34 AM, James Juno ***@***.***> wrote:﻿
Sure but you can save yourself the annoyance that you have to set up the bin_op memory and then free it when you're done, and you guard against future developers not realizing you should not do this for p>1 because the basis_inv methods don't exist for p>1.

**Comment by JunoRavin** [comment]
You're not listening to me. Look at the plots I posted. If you choose to go this route and then later discover spurious oscillations from pre-computing 1/Bmag for p=2 that is your prerogative but it is frankly a foolish thing to do. It can be conservative and still junk.

**Comment by manauref** [comment]
Ok I hear youOn Mar 13, 2024, at 8:09 AM, James Juno ***@***.***> wrote:﻿
You're not listening to me. Look at the plots I posted. If you choose to go this route and then later discover spurious oscillations from pre-computing 1/Bmag for p=2 that is your prerogative but it is frankly a foolish thing to do. It can be conservative and still junk.

**Comment by manauref** [comment]
@JunoRavin it seems that even after computing bmag_inv with basis_inv (you said this is equivalent to weak div for p=1?), energy conservation is still broken in the GkLBO

<img width="752" alt="Screenshot 2024-03-13 at 7 28 53 PM" src="https://github.com/ammarhakim/gkylzero/assets/2220456/98a4b272-5cd2-4929-8db3-2436ab2c246d">

Any idea where else we might be making a mistake?

**Comment by manauref** [comment]
nvm, the test needs to be done turning off collisionless terms. Things work now.
